'use server'

import { GoogleGenerativeAI } from '@google/generative-ai'
// import Groq from 'groq-sdk' // Assuming installed, or use fetch if not.

// Helper to sanitize text for PDF/HTML
function cleanText(text: string) {
    return text.replace(/[*#]/g, '')
}

export async function generateInvoiceHTML(patientName: string, items: any[], total: number, paymentId: string) {
    try {
        const apiKey = process.env.GEMINI_API_KEY
        if (!apiKey) {
            // Fallback to basic HTML if no API key
            return generateFallbackHTML(patientName, items, total, paymentId)
        }

        const genAI = new GoogleGenerativeAI(apiKey)
        const model = genAI.getGenerativeModel({ model: 'gemini-pro' })

        const prompt = `
        You are a billing system for City Hospital.
        Generate a professional HTML Invoice for the following transaction.
        Use Tailwind CSS classes for styling (inline styles are also okay but Tailwind preferred if CDN included).
        Make it look clean, modern, and medical.
        
        Details:
        Patient: ${patientName}
        Date: ${new Date().toLocaleDateString()}
        Payment ID: ${paymentId}
        
        Items:
        ${items.map(i => `- ${i.medicine_name} (Qty: ${i.quantity}) - $${i.price}`).join('\n')}
        
        Total: $${total}

        Return ONLY the HTML code (start with <div id="invoice">). Do not include markdown backticks or explanations.
        Include a header with Hospital Logo (placeholder), Address, and Patient Details.
        Include a table for items.
        Include a footer with "Generated by AI Billing System".
        `

        const result = await model.generateContent(prompt)
        const response = await result.response
        const text = response.text()

        // Clean up markdown code blocks if Gemini adds them
        const html = text.replace(/```html/g, '').replace(/```/g, '')

        return html
    } catch (error) {
        console.error('AI Invoice Error:', error)
        return generateFallbackHTML(patientName, items, total, paymentId)
    }
}

function generateFallbackHTML(patientName: string, items: any[], total: number, paymentId: string) {
    return `
        <div class="p-8 max-w-2xl mx-auto border bg-white text-black font-sans">
            <div class="flex justify-between items-center mb-8 border-b pb-4">
                <div>
                    <h1 class="text-2xl font-bold text-blue-600">City Hospital</h1>
                    <p class="text-sm text-gray-500">123 Medical Drive, Health City</p>
                </div>
                <div class="text-right">
                    <h2 class="text-xl font-bold">INVOICE</h2>
                    <p class="text-sm text-gray-500">#${paymentId.slice(-8).toUpperCase()}</p>
                </div>
            </div>

            <div class="mb-8">
                <p class="font-bold">Bill To:</p>
                <p>${patientName}</p>
                <p class="text-sm text-gray-500">${new Date().toLocaleDateString()}</p>
            </div>

            <table class="w-full mb-8 border-collapse">
                <thead>
                    <tr class="border-b-2 border-gray-200">
                        <th class="text-left py-2">Item</th>
                        <th class="text-right py-2">Qty</th>
                        <th class="text-right py-2">Price</th>
                        <th class="text-right py-2">Total</th>
                    </tr>
                </thead>
                <tbody>
                    ${items.map(item => `
                    <tr class="border-b border-gray-100">
                        <td class="py-2">${item.medicine_name}</td>
                        <td class="text-right py-2">${item.quantity}</td>
                        <td class="text-right py-2">$${item.price.toFixed(2)}</td>
                        <td class="text-right py-2">$${(item.price * item.quantity).toFixed(2)}</td>
                    </tr>
                    `).join('')}
                </tbody>
            </table>

            <div class="flex justify-end text-xl font-bold border-t pt-4">
                <span>Total: $${total.toFixed(2)}</span>
            </div>
            
            <div class="mt-8 text-center text-xs text-gray-400">
                Authorized Signature
            </div>
        </div>
    `
}
