'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { FileText, Download, Pill } from 'lucide-react'
import { safeFormat } from '@/lib/date'
import jsPDF from 'jspdf'

interface Prescription {
    id: string
    drug_name: string
    dosage: string
    frequency: string
    duration: string
    instructions: string
    created_at: string
}

interface PrescriptionCardProps {
    prescriptions: Prescription[]
    patientName: string
}

export function PrescriptionCard({ prescriptions, patientName }: PrescriptionCardProps) {

    const generatePDF = (rxList: Prescription[], single?: Prescription) => {
        const doc = new jsPDF()
        const items = single ? [single] : rxList
        const date = format(new Date(), 'MMMM d, yyyy')

        // Header
        doc.setFillColor(14, 165, 233)
        doc.rect(0, 0, 210, 35, 'F')
        doc.setFontSize(22)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(255, 255, 255)
        doc.text('CareBridge', 20, 18)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.text('Medical Prescription', 20, 27)

        // Patient info
        doc.setTextColor(0, 0, 0)
        doc.setFontSize(11)
        doc.text(`Patient: ${patientName}`, 20, 48)
        doc.text(`Date: ${date}`, 20, 56)
        doc.text(`Prescribed by: CareBridge Hospital`, 20, 64)
        doc.line(20, 70, 190, 70)

        // Rx symbol
        doc.setFontSize(16)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(14, 165, 233)
        doc.text('Rx', 20, 84)
        doc.setTextColor(0, 0, 0)

        let y = 94
        items.forEach((rx, idx) => {
            if (idx > 0) {
                doc.line(20, y - 4, 190, y - 4)
                y += 4
            }
            doc.setFontSize(12)
            doc.setFont('helvetica', 'bold')
            doc.text(`${idx + 1}. ${rx.drug_name}`, 20, y)
            y += 8
            doc.setFontSize(10)
            doc.setFont('helvetica', 'normal')
            doc.text(`   Dosage: ${rx.dosage || '-'}`, 20, y); y += 7
            doc.text(`   Frequency: ${rx.frequency || '-'}`, 20, y); y += 7
            doc.text(`   Duration: ${rx.duration || '-'}`, 20, y); y += 7
            if (rx.instructions) { doc.text(`   Instructions: ${rx.instructions}`, 20, y); y += 7 }
            y += 4
        })

        doc.line(20, y + 4, 190, y + 4)
        doc.setFontSize(9)
        doc.setTextColor(120)
        doc.text('This prescription was generated by CareBridge HMS. Valid for 30 days.', 20, y + 12)

        const filename = single
            ? `prescription-${single.drug_name}-${date}.pdf`
            : `all-prescriptions-${patientName}-${date}.pdf`
        doc.save(filename)
    }

    if (prescriptions.length === 0) {
        return (
            <Card>
                <CardContent className="p-8 text-center text-muted-foreground">
                    <Pill className="h-10 w-10 mx-auto mb-3 opacity-30" />
                    <p className="font-medium">No prescriptions yet.</p>
                    <p className="text-xs mt-1">Prescriptions will appear here after your doctor completes a consultation.</p>
                </CardContent>
            </Card>
        )
    }

    return (
        <div className="space-y-3">
            {/* Download All button */}
            {prescriptions.length > 1 && (
                <div className="flex justify-end">
                    <Button variant="outline" size="sm" onClick={() => generatePDF(prescriptions)}>
                        <Download className="h-4 w-4 mr-2" />
                        Download All ({prescriptions.length})
                    </Button>
                </div>
            )}

            {prescriptions.map((rx) => (
                <Card key={rx.id} className="border-l-4 border-l-primary">
                    <CardHeader className="pb-2 flex flex-row items-center justify-between">
                        <div>
                            <CardTitle className="text-base flex items-center gap-2">
                                <Pill className="h-4 w-4 text-primary" />
                                {rx.drug_name}
                            </CardTitle>
                        </div>
                        <Button size="sm" variant="outline" onClick={() => generatePDF(prescriptions, rx)}>
                            <Download className="h-4 w-4 mr-1" />
                            PDF
                        </Button>
                    </CardHeader>
                    <CardContent className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                        <div>
                            <p className="text-muted-foreground text-xs">Dosage</p>
                            <p className="font-medium">{rx.dosage || '-'}</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground text-xs">Frequency</p>
                            <p className="font-medium">{rx.frequency || '-'}</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground text-xs">Duration</p>
                            <p className="font-medium">{rx.duration || '-'}</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground text-xs">Prescribed On</p>
                            <p className="font-medium">{safeFormat(rx.created_at, 'MMM d, yyyy')}</p>
                        </div>
                        {rx.instructions && (
                            <div className="col-span-2 md:col-span-4 bg-muted/30 rounded p-2">
                                <p className="text-muted-foreground text-xs">Instructions</p>
                                <p className="font-medium">{rx.instructions}</p>
                            </div>
                        )}
                    </CardContent>
                </Card>
            ))}
        </div>
    )
}
