'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { FileText, Download } from 'lucide-react'
import { format } from 'date-fns'
import jsPDF from 'jspdf'

interface Prescription {
    id: string
    drug_name: string
    dosage: string
    frequency: string
    duration: string
    instructions: string
    created_at: string
}

interface PrescriptionCardProps {
    prescriptions: Prescription[]
    patientName: string
}

export function PrescriptionCard({ prescriptions, patientName }: PrescriptionCardProps) {
    const handleDownload = (rx: Prescription) => {
        const doc = new jsPDF()
        const date = format(new Date(rx.created_at), 'MMMM d, yyyy')

        // Header
        doc.setFontSize(20)
        doc.setFont('helvetica', 'bold')
        doc.text('CareBridge', 20, 20)

        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(100)
        doc.text('Medical Prescription', 20, 28)
        doc.line(20, 32, 190, 32)

        // Patient & Date
        doc.setTextColor(0)
        doc.setFontSize(11)
        doc.text(`Patient: ${patientName}`, 20, 42)
        doc.text(`Date: ${date}`, 20, 50)

        if (rx.instructions) {
            doc.text(`Reason: ${rx.instructions}`, 20, 58)
        }

        doc.line(20, 64, 190, 64)

        // Prescription Details
        doc.setFontSize(13)
        doc.setFont('helvetica', 'bold')
        doc.text('Rx', 20, 74)

        doc.setFontSize(11)
        doc.setFont('helvetica', 'normal')
        doc.text(`Drug: ${rx.drug_name}`, 20, 84)
        doc.text(`Dosage: ${rx.dosage || '-'}`, 20, 92)
        doc.text(`Frequency: ${rx.frequency || '-'}`, 20, 100)
        doc.text(`Duration: ${rx.duration || '-'}`, 20, 108)

        if (rx.instructions) {
            doc.text(`Instructions: ${rx.instructions}`, 20, 116)
        }

        doc.line(20, 130, 190, 130)
        doc.setFontSize(9)
        doc.setTextColor(120)
        doc.text('This prescription was generated by CareBridge HMS.', 20, 138)

        doc.save(`prescription-${rx.drug_name}-${date}.pdf`)
    }

    if (prescriptions.length === 0) {
        return (
            <Card>
                <CardContent className="p-8 text-center text-muted-foreground">
                    <FileText className="h-8 w-8 mx-auto mb-2 opacity-50" />
                    <p>No prescriptions yet.</p>
                </CardContent>
            </Card>
        )
    }

    return (
        <div className="space-y-3">
            {prescriptions.map((rx) => (
                <Card key={rx.id}>
                    <CardHeader className="pb-2 flex flex-row items-center justify-between">
                        <CardTitle className="text-base flex items-center gap-2">
                            <FileText className="h-4 w-4 text-primary" />
                            {rx.drug_name}
                        </CardTitle>
                        <Button size="sm" variant="outline" onClick={() => handleDownload(rx)}>
                            <Download className="h-4 w-4 mr-1" />
                            Download PDF
                        </Button>
                    </CardHeader>
                    <CardContent className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                        <div>
                            <p className="text-muted-foreground">Dosage</p>
                            <p className="font-medium">{rx.dosage || '-'}</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground">Frequency</p>
                            <p className="font-medium">{rx.frequency || '-'}</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground">Duration</p>
                            <p className="font-medium">{rx.duration || '-'}</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground">Date</p>
                            <p className="font-medium">{format(new Date(rx.created_at), 'MMM d, yyyy')}</p>
                        </div>
                        {rx.instructions && (
                            <div className="col-span-2 md:col-span-4">
                                <p className="text-muted-foreground">Instructions</p>
                                <p className="font-medium">{rx.instructions}</p>
                            </div>
                        )}
                    </CardContent>
                </Card>
            ))}
        </div>
    )
}
